version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb+srv://hoangluudev17_db_user:2BrOmQKsN1tlRvj7@soty.xjhjgrw.mongodb.net/dev?retryWrites=true&w=majority&appName=soty

volumes:
  mongo_data:
