services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: soty-be
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    environment:
      DATABASE_URL: ${DB_MONGO_URI}
      REDIS_URL: ${REDIS_URL}
      USER_CACHE_TTL: ${USER_CACHE_TTL}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    working_dir: /workspace
    command: ['npm', 'run', 'start:dev']
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: soty-redis
    ports:
      - '6379:6379'
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--appendfsync',
        'everysec',
        '--requirepass',
        'yourRedisPassword123',
      ]
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge
